version: '3.8'

services:
  app:
    build: .
    ports:
      - 3001:${PORT}
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL}
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - CORE_SERVICE_URL=${CORE_SERVICE_URL}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - PORT=3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
