version: '3'

services:
  api-gateway:
    build: .
    ports:
      - 3001:${PORT}
    depends_on:
      - redis
     
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - CORE_SERVICE_URL=${CORE_SERVICE_URL}
    networks:
      - mas-hms-network
    volumes:
      - .:/app  
      - /app/node_modules
  redis:
    image: redis:6.2
    ports:
      - 6380:6379
    volumes:
      - redis-data:/data
       
    networks:
      - mas-hms-network
    
volumes:
  redis-data:

networks:
  mas-hms-network:
    external: true
