version: '3'

services:
  app:
    build: .
    ports:
      - 3001:${PORT}
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL= ${DEV_DATABASE_URL}
      - REDIS_URL= ${REDIS_URL}
  mongo:
    image: mongo:latest    
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db  
  redis:
    image: redis:6.2
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data    
volumes:
  mongo-data:
  redis-data:      