export enum Core_Service_Api_Path {
  TESR = '/test',
  ORDER = '/order',
  ACCOUNT = '/account',
  BACTERIA = '/bacteria',
  SENSITIVITY = '/sensitivity',
  CONDITION = '/condition',
  PDRV = '/pdrv',
  SPECIMEN = '/specimen',
  TESTTUBE = '/test-tube',
  DOCTOR = '/doctor',
  TRANSACTION = '/transaction',
  PATIENT = '/patient',
  TESTREPORT = '/testReport',
  HOSPITALGROUP = '/hospitalGroup',
  DEPARTMENTS = '/departments',
  REPORTGROUP = '/reportGroup',
  REPORT_TYPE_GROUP = '/reportTypeGroup',
  REPORT_Type = '/reportType',
  REPORT_TEST = '/report/test',
  COMMENT = '/comment',
  SEAL = '/seal',
  MISCELLANEOUS = '/miscellaneous',
  INCOMESTATEMENT = '/income-statemnet',
  REFUND = '/refund',
  FINANCIALREPORT = '/financialReport',
  COMPANYINFO = '/company-info'
}
